# Introduction

So, Today we are going to work on a new project called Breast Cancer Prediction using scikit-learn various models and calulate the accuracy of best model.
A cancer that forms in the cells of the breasts.

Breast cancer can occur in women and rarely in men.

Symptoms of breast cancer include a lump in the breast, bloody discharge from the nipple and changes in the shape or texture of the nipple or breast.

Its treatment depends on the stage of cancer. It may consist of chemotherapy, radiation, hormone therapy and surgery.

A tumor is an abnormal lump or growth of cells. When the cells in the tumor are normal, it is benign. Something just went wrong, and they overgrew and produced a lump. When the cells are abnormal and can grow uncontrollably, they are cancerous cells, and the tumor is malignant.

## Dataset
Based on whether the tumor is Benign or malignant there is a dataset readily available in the sklearn model and we are going to deal with it to train various scikit-learn models
OR
Alternatively, we can download the dataset from the kaggle <a href="https://www.kaggle.com/uciml/breast-cancer-wisconsin-data" target="">BREAST CANCER PREDICTION DATASET</a>

First of all load the model from the sklearn and also numpy for various numerical computation

## Loading Dataset

In [1]:
# importing numoy for numerical operations
import numpy as np
# importing dataset from sklearn
import sklearn.datasets as data

Now, load the breast cancer data from various avaliable datasets in sklearn 

In [2]:
# initializing breast_cancer dataset
breast_cancer=data.load_breast_cancer()

Take a look at the data by print attribute

In [3]:
# taking a look at the data
print(breast_cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

The data is in the form of dictionary format with various values in the *features_names* which are nothing but the independant variables columns and their values are in the *data* and the *target_names* is nothing but the target or dependant variables columns which is having two values in it i.e. 'malignant' and 'benign' and their values are in *target* 

So, let us divide the dependant variables in X and independant variable in Y.

In [4]:
# Divinding features and target columns

# feature data
X=breast_cancer.data

# target data
Y=breast_cancer.target

Taking a glance at the data after division

In [5]:
# printing feature data
print(X)

# printing target data
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

Checking the shape of the data by shape attribute

In [6]:
# shape of the data
print(X.shape,Y.shape)
# So, the X has 30 columns which means 30 features and 
# Y has 1 column in which two values bengin and malignant and both has 569 rows.

(569, 30) (569,)


Now, Since the data is in dictionary form we can easily transform this into dataframe by pandas

# Analyzing the data

In [7]:
# importing pandas
import pandas as pd

After importing pandas we can convert data into dataframe attribute in which we will pass the X varible first and the respective columns name which is in featue_names

In [8]:
# tranform data into dataframe
df= pd.DataFrame(breast_cancer.data,columns=breast_cancer.feature_names)

Then, we will add the target variable in a new column called class

In [9]:
# adding target column
df['class']=breast_cancer.target

Taking a glance at the dataset by pandas head attribute

In [10]:
# printing first 4 rows
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

Or, you can download the dataset from the Kaggle (see the INTRODUCTION-DATASETS) and upload it in the same folder as our .ipynb file for only our convinience

`Note- In Kaggle Dataset, at the target columns 0 means 'malignant' and 1 means 'benign'`

Loading the dataset from the downloaded dataset file using and read it using read_csv attribute in pandas

In [11]:
# loading the dataset
df.to_csv('breast_cancer_prediction.csv',index=False)

Seeing the statistical describtion of the data by describe attribute

In [12]:
# statistical analysis
df.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

Counting the values in the target column i.e. class column by using value_counts attribute

In [13]:
# counting the values in class
df['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

Cross checking the target values available 

In [14]:
# printing the target names 
print(breast_cancer.target_names)

['malignant' 'benign']


Looking at the impact of the targets on various dependent variable by grouping by the target class and then taking a mean of that group and finally printing the data

In [15]:
# grouping the class column and taking the mean
class_group=df.groupby('class').mean()

# printing the class_group
print(class_group) 

       mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class        

It is seen from the above table that malignant has higher values than benign which is obvious because 1-benign tumor can be cured while 0-malignant tumor is somewhat danger.

Now, after analyzing we will split the data and then train it with various scikit-learn models

# Train-Test Split

Splitting the data into train and test data for training and testing the models

In [16]:
# importing train-test split from sklearn
from sklearn.model_selection import train_test_split as tsp

In [17]:
# splitting the data into train and test
x_train,x_test,y_train,y_test=tsp(X,Y,test_size=0.1)

Now, we will see that the target data is uniformly split in train and test by checking each data mean by using mean attribute

In [18]:
# mean of original data
print(Y.mean())

# mean of train data
print(y_train.mean())

# mean of test data
print(y_test.mean())

0.6274165202108963
0.626953125
0.631578947368421


It is been observed that the mean shows large variation for the 3 forms of data.

So, we will use the stratify attribute to split the data into equal uniformity

In [19]:
# again splitting the data by using stratify attribute
x_train,x_test,y_train,y_test=tsp(X,Y,test_size=0.1,stratify=Y,random_state=1)

We can cross check the uniformity by again checking the mean of 3 forms of data.

In [20]:
# mean of original data
print(Y.mean())

# mean of train data
print(y_train.mean())

# mean of test data
print(y_test.mean())

0.6274165202108963
0.626953125
0.631578947368421


So, now the data is uniformly distributed in train and test for target variable.

And we are ready to train our models

We will train our models in two models-
* Logistic Regression
* K-Nearest Neighbours

And then check the accuracy for both the models for training and testing data to give the best model for predicting

# Using LogisticRegression

We will import LogisticRegression model from the sklearn and also accruracy score to check the accuracy of the models

In [21]:
# importing Logistic Regression model
from sklearn.linear_model import LogisticRegression

# importing accuracy score from sklearn
from sklearn.metrics import accuracy_score

Then, we will initilize an object of Logistic Regression for futher computation

In [22]:
# intialing the model
log=LogisticRegression()

Training the model by fitting the train data into the model using fit attribute

In [23]:
# fitting the model
log.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

After training,its time to test the model and check its accuracy on both (test and train data)

### On Train data-

In [24]:
# testing the model on train data
x_train_pred=log.predict(x_train)

# checking its accuracy
acc_log=accuracy_score(y_train,x_train_pred)
print('Accuracy on train data:',acc_log)

Accuracy on train data: 0.951171875


In [25]:
# testing the model on test data
x_test_pred=log.predict(x_test)

# checking its accuracy
acc=accuracy_score(y_test,x_test_pred)
print('Accuracy on test data:',acc)

Accuracy on test data: 0.9298245614035088


# Using K-NearestNeighbours

Now, we will check the KNearest model by importing it from sklearn

In [26]:
# importing the model
from sklearn.neighbors import KNeighborsClassifier

Initializing the KNearest for k = 3 

In [27]:
# initialising the model
knn=KNeighborsClassifier(n_neighbors=3)

Training the model by fit attribute

In [28]:
# training the data
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

Finally, we will test the model and check the accuracy of the model using accuracy score which was initialised during LogisticRegression

### On training data-

In [29]:
# testing the training data
predict=knn.predict(x_train)

# checking its accuracy
acc_knn=accuracy_score(y_train,predict)
print("Accuracy on train data :",acc_knn)

Accuracy on train data : 0.955078125


In [30]:
# testing the test data
predict=knn.predict(x_test)

# checking its accuracy
acc=accuracy_score(y_test,predict)
print("Accuracy on test data :",acc)

Accuracy on test data : 0.9298245614035088


# Checking the best model

Checking the best model by comparing accuracy of both model

In [31]:
# comparing accuracy of both models
if acc_log>acc_knn:
    print(f'Logistic Regression is more efficient than K-NearestNeighbours with an accuracy lead of {(acc_log-acc_knn)*100}')
else:
    print(f'K-NearestNeighbours is more efficient Logistic Regression than  with an accuracy lead of {(acc_knn-acc_log)*100}')

K-NearestNeighbours is more efficient Logistic Regression than  with an accuracy lead of 0.390625


# Validating

Now, it is been proved that KNN more efficient,So, let us check our model by passing a random value in the model

In [32]:
# taking a random value from the dataset
input=(13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

# converting the input into numpy array
inp_array=np.asarray(input)

# checking the shape
inp_array.shape

(30,)

Reshaping the numpy array of shape(30,1) for into a shape of (1,30) for predicitng the output

In [33]:
# reshaping the numpy array
inp_array_reshape=inp_array.reshape(1,-1)

# checking the shape after reshaping
inp_array_reshape.shape

(1, 30)

Predicting the output by placing the reshape numpy array in KNN model

In [34]:
# Checking the reshape data
prediction=knn.predict(inp_array_reshape)

# printing the prediction
print(prediction)

[1]


Passing a normal if-else statement, for better understanding the output

In [35]:
# printing the result
if prediction[0]==0:
    print('The breast Cancer is Malignant')
else:
    print("The breast Cancer is Benign")

The breast Cancer is Benign


# Conclusion

1. So we have trained two classification for breast cancer prediction.
2. And KNN is found to be the best model in comparison with LogisticRegresstion.
3. Finally we have checked the model by passing a random value in the KNN model.

# Thank You

Thank you for reading this blog and hope you have learn something new. I will comeback with a new project, any suggestion or appreciation is most welcome in the comments. 